#INCLUDE "PROTHEUS.CH"
#INCLUDE "APWEBSRV.CH"

/* ===============================================================================
WSDL Location    AllTrim(GetMv("MV_XWSMOBI"))WS_LOGIN_BENEFICIARIO.apw?WSDL
Gerado em        12/03/15 17:54:40
Observações      Código-Fonte gerado por ADVPL WSDL Client 1.120703
                 Alterações neste arquivo podem causar funcionamento incorreto
                 e serão perdidas caso o código-fonte seja gerado novamente.
=============================================================================== */

User Function _BZQMKOS ; Return  // "dummy" function - Internal Use 

/* -------------------------------------------------------------------------------
WSDL Service WSWS_LOGIN_BENEFICIARIO
------------------------------------------------------------------------------- */

WSCLIENT WSWS_LOGIN_BENEFICIARIO

	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD WS_BENEFICIARIO_ALTERACAO_CADASTRAL
	WSMETHOD WS_BENEFICIARIO_CRIAR_ACESSO
	WSMETHOD WS_BENEFICIARIO_LEMBRAR_USUARIO
	WSMETHOD WS_BENEFICIARIO_LOGIN
	WSMETHOD WS_BENEFICIARIO_REDEFINIR_SENHA
	WSMETHOD WS_BENEFICIARIO_TROCAR_SENHA

	WSDATA   _URL                      AS String
	WSDATA   _HEADOUT                  AS Array of String
	WSDATA   _COOKIES                  AS Array of String
	WSDATA   cBENEFICIARIO_CPF         AS string
	WSDATA   dBENEFICIARIO_DATA_NASCIMENTO AS date
	WSDATA   oWSWS_BENEFICIARIO_ALTERACAO_CADASTRALRESULT AS WS_LOGIN_BENEFICIARIO_ST_USUARIO_ACESSO
	WSDATA   cBENEFICIARIO_MATRICULA   AS string
	WSDATA   cBENEFICIARIO_EMAIL       AS string
	WSDATA   cUSER_MOBILE_SENHA        AS string
	WSDATA   oWSWS_BENEFICIARIO_CRIAR_ACESSORESULT AS WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR
	WSDATA   oWSWS_BENEFICIARIO_LEMBRAR_USUARIORESULT AS WS_LOGIN_BENEFICIARIO_ST_USUARIO_ACESSO
	WSDATA   cUSER_MOBILE_LOGIN_TIPO   AS string
	WSDATA   cUSER_MOBILE_LOGIN        AS string
	WSDATA   cUSER_MOBILE_LOGIN_ORIGEM AS string
	WSDATA   oWSWS_BENEFICIARIO_LOGINRESULT AS WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR
	WSDATA   oWSWS_BENEFICIARIO_REDEFINIR_SENHARESULT AS WS_LOGIN_BENEFICIARIO_ST_REDEFINE_SENHA
	WSDATA   cUSER_MOBILE_NOVA_SENHA   AS string
	WSDATA   cHASH_TROCA_SENHA         AS string
	WSDATA   oWSWS_BENEFICIARIO_TROCAR_SENHARESULT AS WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR

ENDWSCLIENT

WSMETHOD NEW WSCLIENT WSWS_LOGIN_BENEFICIARIO
::Init()
If !FindFunction("XMLCHILDEX")
	UserException("O Código-Fonte Client atual requer os executáveis do Protheus Build [7.00.121227P-20131106] ou superior. Atualize o Protheus ou gere o Código-Fonte novamente utilizando o Build atual.")
EndIf
Return Self

WSMETHOD INIT WSCLIENT WSWS_LOGIN_BENEFICIARIO
	::oWSWS_BENEFICIARIO_ALTERACAO_CADASTRALRESULT := WS_LOGIN_BENEFICIARIO_ST_USUARIO_ACESSO():New()
	::oWSWS_BENEFICIARIO_CRIAR_ACESSORESULT := WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR():New()
	::oWSWS_BENEFICIARIO_LEMBRAR_USUARIORESULT := WS_LOGIN_BENEFICIARIO_ST_USUARIO_ACESSO():New()
	::oWSWS_BENEFICIARIO_LOGINRESULT := WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR():New()
	::oWSWS_BENEFICIARIO_REDEFINIR_SENHARESULT := WS_LOGIN_BENEFICIARIO_ST_REDEFINE_SENHA():New()
	::oWSWS_BENEFICIARIO_TROCAR_SENHARESULT := WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR():New()
Return

WSMETHOD RESET WSCLIENT WSWS_LOGIN_BENEFICIARIO
	::cBENEFICIARIO_CPF  := NIL 
	::dBENEFICIARIO_DATA_NASCIMENTO := NIL 
	::oWSWS_BENEFICIARIO_ALTERACAO_CADASTRALRESULT := NIL 
	::cBENEFICIARIO_MATRICULA := NIL 
	::cBENEFICIARIO_EMAIL := NIL 
	::cUSER_MOBILE_SENHA := NIL 
	::oWSWS_BENEFICIARIO_CRIAR_ACESSORESULT := NIL 
	::oWSWS_BENEFICIARIO_LEMBRAR_USUARIORESULT := NIL 
	::cUSER_MOBILE_LOGIN_TIPO := NIL 
	::cUSER_MOBILE_LOGIN := NIL 
	::cUSER_MOBILE_LOGIN_ORIGEM := NIL 
	::oWSWS_BENEFICIARIO_LOGINRESULT := NIL 
	::oWSWS_BENEFICIARIO_REDEFINIR_SENHARESULT := NIL 
	::cUSER_MOBILE_NOVA_SENHA := NIL 
	::cHASH_TROCA_SENHA  := NIL 
	::oWSWS_BENEFICIARIO_TROCAR_SENHARESULT := NIL 
	::Init()
Return

WSMETHOD CLONE WSCLIENT WSWS_LOGIN_BENEFICIARIO
Local oClone := WSWS_LOGIN_BENEFICIARIO():New()
	oClone:_URL          := ::_URL 
	oClone:cBENEFICIARIO_CPF := ::cBENEFICIARIO_CPF
	oClone:dBENEFICIARIO_DATA_NASCIMENTO := ::dBENEFICIARIO_DATA_NASCIMENTO
	oClone:oWSWS_BENEFICIARIO_ALTERACAO_CADASTRALRESULT :=  IIF(::oWSWS_BENEFICIARIO_ALTERACAO_CADASTRALRESULT = NIL , NIL ,::oWSWS_BENEFICIARIO_ALTERACAO_CADASTRALRESULT:Clone() )
	oClone:cBENEFICIARIO_MATRICULA := ::cBENEFICIARIO_MATRICULA
	oClone:cBENEFICIARIO_EMAIL := ::cBENEFICIARIO_EMAIL
	oClone:cUSER_MOBILE_SENHA := ::cUSER_MOBILE_SENHA
	oClone:oWSWS_BENEFICIARIO_CRIAR_ACESSORESULT :=  IIF(::oWSWS_BENEFICIARIO_CRIAR_ACESSORESULT = NIL , NIL ,::oWSWS_BENEFICIARIO_CRIAR_ACESSORESULT:Clone() )
	oClone:oWSWS_BENEFICIARIO_LEMBRAR_USUARIORESULT :=  IIF(::oWSWS_BENEFICIARIO_LEMBRAR_USUARIORESULT = NIL , NIL ,::oWSWS_BENEFICIARIO_LEMBRAR_USUARIORESULT:Clone() )
	oClone:cUSER_MOBILE_LOGIN_TIPO := ::cUSER_MOBILE_LOGIN_TIPO
	oClone:cUSER_MOBILE_LOGIN := ::cUSER_MOBILE_LOGIN
	oClone:cUSER_MOBILE_LOGIN_ORIGEM := ::cUSER_MOBILE_LOGIN_ORIGEM
	oClone:oWSWS_BENEFICIARIO_LOGINRESULT :=  IIF(::oWSWS_BENEFICIARIO_LOGINRESULT = NIL , NIL ,::oWSWS_BENEFICIARIO_LOGINRESULT:Clone() )
	oClone:oWSWS_BENEFICIARIO_REDEFINIR_SENHARESULT :=  IIF(::oWSWS_BENEFICIARIO_REDEFINIR_SENHARESULT = NIL , NIL ,::oWSWS_BENEFICIARIO_REDEFINIR_SENHARESULT:Clone() )
	oClone:cUSER_MOBILE_NOVA_SENHA := ::cUSER_MOBILE_NOVA_SENHA
	oClone:cHASH_TROCA_SENHA := ::cHASH_TROCA_SENHA
	oClone:oWSWS_BENEFICIARIO_TROCAR_SENHARESULT :=  IIF(::oWSWS_BENEFICIARIO_TROCAR_SENHARESULT = NIL , NIL ,::oWSWS_BENEFICIARIO_TROCAR_SENHARESULT:Clone() )
Return oClone

// WSDL Method WS_BENEFICIARIO_ALTERACAO_CADASTRAL of Service WSWS_LOGIN_BENEFICIARIO

WSMETHOD WS_BENEFICIARIO_ALTERACAO_CADASTRAL WSSEND cBENEFICIARIO_CPF,dBENEFICIARIO_DATA_NASCIMENTO WSRECEIVE oWSWS_BENEFICIARIO_ALTERACAO_CADASTRALRESULT WSCLIENT WSWS_LOGIN_BENEFICIARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WS_BENEFICIARIO_ALTERACAO_CADASTRAL xmlns="'+AllTrim(GetMv("MV_XWSMBL2"))+'">'
cSoap += WSSoapValue("BENEFICIARIO_CPF", ::cBENEFICIARIO_CPF, cBENEFICIARIO_CPF , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("BENEFICIARIO_DATA_NASCIMENTO", ::dBENEFICIARIO_DATA_NASCIMENTO, dBENEFICIARIO_DATA_NASCIMENTO , "date", .F. , .F., 0 , NIL, .F.) 
cSoap += "</WS_BENEFICIARIO_ALTERACAO_CADASTRAL>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	AllTrim(GetMv("MV_XWSMBL2"))+"WS_BENEFICIARIO_ALTERACAO_CADASTRAL",; 
	"DOCUMENT",AllTrim(GetMv("MV_XWSMBL2")),,"1.031217",; 
	AllTrim(GetMv("MV_XWSMBL1"))+"WS_LOGIN_BENEFICIARIO.apw")

::Init()
::oWSWS_BENEFICIARIO_ALTERACAO_CADASTRALRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WS_BENEFICIARIO_ALTERACAO_CADASTRALRESPONSE:_WS_BENEFICIARIO_ALTERACAO_CADASTRALRESULT","ST_USUARIO_ACESSO",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WS_BENEFICIARIO_CRIAR_ACESSO of Service WSWS_LOGIN_BENEFICIARIO

WSMETHOD WS_BENEFICIARIO_CRIAR_ACESSO WSSEND cBENEFICIARIO_MATRICULA,cBENEFICIARIO_CPF,dBENEFICIARIO_DATA_NASCIMENTO,cBENEFICIARIO_EMAIL,cUSER_MOBILE_SENHA WSRECEIVE oWSWS_BENEFICIARIO_CRIAR_ACESSORESULT WSCLIENT WSWS_LOGIN_BENEFICIARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WS_BENEFICIARIO_CRIAR_ACESSO xmlns="'+AllTrim(GetMv("MV_XWSMBL2"))+'">'
cSoap += WSSoapValue("BENEFICIARIO_MATRICULA", ::cBENEFICIARIO_MATRICULA, cBENEFICIARIO_MATRICULA , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("BENEFICIARIO_CPF", ::cBENEFICIARIO_CPF, cBENEFICIARIO_CPF , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("BENEFICIARIO_DATA_NASCIMENTO", ::dBENEFICIARIO_DATA_NASCIMENTO, dBENEFICIARIO_DATA_NASCIMENTO , "date", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("BENEFICIARIO_EMAIL", ::cBENEFICIARIO_EMAIL, cBENEFICIARIO_EMAIL , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("USER_MOBILE_SENHA", ::cUSER_MOBILE_SENHA, cUSER_MOBILE_SENHA , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += "</WS_BENEFICIARIO_CRIAR_ACESSO>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	AllTrim(GetMv("MV_XWSMBL2"))+"WS_BENEFICIARIO_CRIAR_ACESSO",; 
	"DOCUMENT",AllTrim(GetMv("MV_XWSMBL2")),,"1.031217",; 
	AllTrim(GetMv("MV_XWSMBL1"))+"WS_LOGIN_BENEFICIARIO.apw")

::Init()
::oWSWS_BENEFICIARIO_CRIAR_ACESSORESULT:SoapRecv( WSAdvValue( oXmlRet,"_WS_BENEFICIARIO_CRIAR_ACESSORESPONSE:_WS_BENEFICIARIO_CRIAR_ACESSORESULT","ST_GRUPO_FAMILIAR",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WS_BENEFICIARIO_LEMBRAR_USUARIO of Service WSWS_LOGIN_BENEFICIARIO

WSMETHOD WS_BENEFICIARIO_LEMBRAR_USUARIO WSSEND cBENEFICIARIO_CPF,dBENEFICIARIO_DATA_NASCIMENTO WSRECEIVE oWSWS_BENEFICIARIO_LEMBRAR_USUARIORESULT WSCLIENT WSWS_LOGIN_BENEFICIARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WS_BENEFICIARIO_LEMBRAR_USUARIO xmlns="'+AllTrim(GetMv("MV_XWSMBL2"))+'">'
cSoap += WSSoapValue("BENEFICIARIO_CPF", ::cBENEFICIARIO_CPF, cBENEFICIARIO_CPF , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("BENEFICIARIO_DATA_NASCIMENTO", ::dBENEFICIARIO_DATA_NASCIMENTO, dBENEFICIARIO_DATA_NASCIMENTO , "date", .F. , .F., 0 , NIL, .F.) 
cSoap += "</WS_BENEFICIARIO_LEMBRAR_USUARIO>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	AllTrim(GetMv("MV_XWSMBL2"))+"WS_BENEFICIARIO_LEMBRAR_USUARIO",; 
	"DOCUMENT",AllTrim(GetMv("MV_XWSMBL2")),,"1.031217",; 
	AllTrim(GetMv("MV_XWSMBL1"))+"WS_LOGIN_BENEFICIARIO.apw")

::Init()
::oWSWS_BENEFICIARIO_LEMBRAR_USUARIORESULT:SoapRecv( WSAdvValue( oXmlRet,"_WS_BENEFICIARIO_LEMBRAR_USUARIORESPONSE:_WS_BENEFICIARIO_LEMBRAR_USUARIORESULT","ST_USUARIO_ACESSO",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WS_BENEFICIARIO_LOGIN of Service WSWS_LOGIN_BENEFICIARIO

WSMETHOD WS_BENEFICIARIO_LOGIN WSSEND cUSER_MOBILE_LOGIN_TIPO,cUSER_MOBILE_LOGIN,cUSER_MOBILE_SENHA,cUSER_MOBILE_LOGIN_ORIGEM WSRECEIVE oWSWS_BENEFICIARIO_LOGINRESULT WSCLIENT WSWS_LOGIN_BENEFICIARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WS_BENEFICIARIO_LOGIN xmlns="'+AllTrim(GetMv("MV_XWSMBL2"))+'">'
cSoap += WSSoapValue("USER_MOBILE_LOGIN_TIPO", ::cUSER_MOBILE_LOGIN_TIPO, cUSER_MOBILE_LOGIN_TIPO , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("USER_MOBILE_LOGIN", ::cUSER_MOBILE_LOGIN, cUSER_MOBILE_LOGIN , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("USER_MOBILE_SENHA", ::cUSER_MOBILE_SENHA, cUSER_MOBILE_SENHA , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("USER_MOBILE_LOGIN_ORIGEM", ::cUSER_MOBILE_LOGIN_ORIGEM, cUSER_MOBILE_LOGIN_ORIGEM , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += "</WS_BENEFICIARIO_LOGIN>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	AllTrim(GetMv("MV_XWSMBL2"))+"WS_BENEFICIARIO_LOGIN",; 
	"DOCUMENT",AllTrim(GetMv("MV_XWSMBL2")),,"1.031217",; 
	AllTrim(GetMv("MV_XWSMBL1"))+"WS_LOGIN_BENEFICIARIO.apw")

::Init()
::oWSWS_BENEFICIARIO_LOGINRESULT:SoapRecv( WSAdvValue( oXmlRet,"_WS_BENEFICIARIO_LOGINRESPONSE:_WS_BENEFICIARIO_LOGINRESULT","ST_GRUPO_FAMILIAR",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WS_BENEFICIARIO_REDEFINIR_SENHA of Service WSWS_LOGIN_BENEFICIARIO

WSMETHOD WS_BENEFICIARIO_REDEFINIR_SENHA WSSEND cBENEFICIARIO_MATRICULA,cBENEFICIARIO_CPF,dBENEFICIARIO_DATA_NASCIMENTO WSRECEIVE oWSWS_BENEFICIARIO_REDEFINIR_SENHARESULT WSCLIENT WSWS_LOGIN_BENEFICIARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WS_BENEFICIARIO_REDEFINIR_SENHA xmlns="'+AllTrim(GetMv("MV_XWSMBL2"))+'">'
cSoap += WSSoapValue("BENEFICIARIO_MATRICULA", ::cBENEFICIARIO_MATRICULA, cBENEFICIARIO_MATRICULA , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("BENEFICIARIO_CPF", ::cBENEFICIARIO_CPF, cBENEFICIARIO_CPF , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("BENEFICIARIO_DATA_NASCIMENTO", ::dBENEFICIARIO_DATA_NASCIMENTO, dBENEFICIARIO_DATA_NASCIMENTO , "date", .F. , .F., 0 , NIL, .F.) 
cSoap += "</WS_BENEFICIARIO_REDEFINIR_SENHA>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	AllTrim(GetMv("MV_XWSMBL2"))+"WS_BENEFICIARIO_REDEFINIR_SENHA",; 
	"DOCUMENT",AllTrim(GetMv("MV_XWSMBL2")),,"1.031217",; 
	AllTrim(GetMv("MV_XWSMBL1"))+"WS_LOGIN_BENEFICIARIO.apw")

::Init()
::oWSWS_BENEFICIARIO_REDEFINIR_SENHARESULT:SoapRecv( WSAdvValue( oXmlRet,"_WS_BENEFICIARIO_REDEFINIR_SENHARESPONSE:_WS_BENEFICIARIO_REDEFINIR_SENHARESULT","ST_REDEFINE_SENHA",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.

// WSDL Method WS_BENEFICIARIO_TROCAR_SENHA of Service WSWS_LOGIN_BENEFICIARIO

WSMETHOD WS_BENEFICIARIO_TROCAR_SENHA WSSEND cBENEFICIARIO_MATRICULA,cBENEFICIARIO_CPF,dBENEFICIARIO_DATA_NASCIMENTO,cUSER_MOBILE_SENHA,cUSER_MOBILE_NOVA_SENHA,cHASH_TROCA_SENHA WSRECEIVE oWSWS_BENEFICIARIO_TROCAR_SENHARESULT WSCLIENT WSWS_LOGIN_BENEFICIARIO
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<WS_BENEFICIARIO_TROCAR_SENHA xmlns="'+AllTrim(GetMv("MV_XWSMBL2"))+'">'
cSoap += WSSoapValue("BENEFICIARIO_MATRICULA", ::cBENEFICIARIO_MATRICULA, cBENEFICIARIO_MATRICULA , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("BENEFICIARIO_CPF", ::cBENEFICIARIO_CPF, cBENEFICIARIO_CPF , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("BENEFICIARIO_DATA_NASCIMENTO", ::dBENEFICIARIO_DATA_NASCIMENTO, dBENEFICIARIO_DATA_NASCIMENTO , "date", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("USER_MOBILE_SENHA", ::cUSER_MOBILE_SENHA, cUSER_MOBILE_SENHA , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("USER_MOBILE_NOVA_SENHA", ::cUSER_MOBILE_NOVA_SENHA, cUSER_MOBILE_NOVA_SENHA , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += WSSoapValue("HASH_TROCA_SENHA", ::cHASH_TROCA_SENHA, cHASH_TROCA_SENHA , "string", .F. , .F., 0 , NIL, .F.) 
cSoap += "</WS_BENEFICIARIO_TROCAR_SENHA>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	AllTrim(GetMv("MV_XWSMBL2"))+"WS_BENEFICIARIO_TROCAR_SENHA",; 
	"DOCUMENT",AllTrim(GetMv("MV_XWSMBL2")),,"1.031217",; 
	AllTrim(GetMv("MV_XWSMBL1"))+"WS_LOGIN_BENEFICIARIO.apw")

::Init()
::oWSWS_BENEFICIARIO_TROCAR_SENHARESULT:SoapRecv( WSAdvValue( oXmlRet,"_WS_BENEFICIARIO_TROCAR_SENHARESPONSE:_WS_BENEFICIARIO_TROCAR_SENHARESULT","ST_GRUPO_FAMILIAR",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.


// WSDL Data Structure ST_USUARIO_ACESSO

WSSTRUCT WS_LOGIN_BENEFICIARIO_ST_USUARIO_ACESSO
	WSDATA   oWSRETORNO_ALERTAS        AS WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA OPTIONAL
	WSDATA   oWSRETORNO_CRITICAS       AS WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA OPTIONAL
	WSDATA   oWSRETORNO_DADOS          AS WS_LOGIN_BENEFICIARIO_ARRAYOFUSUARIO_ACESSO OPTIONAL
	WSDATA   lRETORNO_STATUS           AS boolean OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_ST_USUARIO_ACESSO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_ST_USUARIO_ACESSO
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_ST_USUARIO_ACESSO
	Local oClone := WS_LOGIN_BENEFICIARIO_ST_USUARIO_ACESSO():NEW()
	oClone:oWSRETORNO_ALERTAS   := IIF(::oWSRETORNO_ALERTAS = NIL , NIL , ::oWSRETORNO_ALERTAS:Clone() )
	oClone:oWSRETORNO_CRITICAS  := IIF(::oWSRETORNO_CRITICAS = NIL , NIL , ::oWSRETORNO_CRITICAS:Clone() )
	oClone:oWSRETORNO_DADOS     := IIF(::oWSRETORNO_DADOS = NIL , NIL , ::oWSRETORNO_DADOS:Clone() )
	oClone:lRETORNO_STATUS      := ::lRETORNO_STATUS
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_ST_USUARIO_ACESSO
	Local oNode1
	Local oNode2
	Local oNode3
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_RETORNO_ALERTAS","ARRAYOFALERTA",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSRETORNO_ALERTAS := WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA():New()
		::oWSRETORNO_ALERTAS:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_RETORNO_CRITICAS","ARRAYOFCRITICA",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSRETORNO_CRITICAS := WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA():New()
		::oWSRETORNO_CRITICAS:SoapRecv(oNode2)
	EndIf
	oNode3 :=  WSAdvValue( oResponse,"_RETORNO_DADOS","ARRAYOFUSUARIO_ACESSO",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode3 != NIL
		::oWSRETORNO_DADOS := WS_LOGIN_BENEFICIARIO_ARRAYOFUSUARIO_ACESSO():New()
		::oWSRETORNO_DADOS:SoapRecv(oNode3)
	EndIf
	::lRETORNO_STATUS    :=  WSAdvValue( oResponse,"_RETORNO_STATUS","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
Return

// WSDL Data Structure ST_GRUPO_FAMILIAR

WSSTRUCT WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR
	WSDATA   oWSRETORNO_ACESSOS        AS WS_LOGIN_BENEFICIARIO_ACESSO OPTIONAL
	WSDATA   oWSRETORNO_ALERTAS        AS WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA OPTIONAL
	WSDATA   oWSRETORNO_CRITICAS       AS WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA OPTIONAL
	WSDATA   oWSRETORNO_DADOS          AS WS_LOGIN_BENEFICIARIO_ARRAYOFBENEFICIARIO OPTIONAL
	WSDATA   lRETORNO_STATUS           AS boolean OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR
	Local oClone := WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR():NEW()
	oClone:oWSRETORNO_ACESSOS   := IIF(::oWSRETORNO_ACESSOS = NIL , NIL , ::oWSRETORNO_ACESSOS:Clone() )
	oClone:oWSRETORNO_ALERTAS   := IIF(::oWSRETORNO_ALERTAS = NIL , NIL , ::oWSRETORNO_ALERTAS:Clone() )
	oClone:oWSRETORNO_CRITICAS  := IIF(::oWSRETORNO_CRITICAS = NIL , NIL , ::oWSRETORNO_CRITICAS:Clone() )
	oClone:oWSRETORNO_DADOS     := IIF(::oWSRETORNO_DADOS = NIL , NIL , ::oWSRETORNO_DADOS:Clone() )
	oClone:lRETORNO_STATUS      := ::lRETORNO_STATUS
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_ST_GRUPO_FAMILIAR
	Local oNode1
	Local oNode2
	Local oNode3
	Local oNode4
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_RETORNO_ACESSOS","ACESSO",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSRETORNO_ACESSOS := WS_LOGIN_BENEFICIARIO_ACESSO():New()
		::oWSRETORNO_ACESSOS:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_RETORNO_ALERTAS","ARRAYOFALERTA",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSRETORNO_ALERTAS := WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA():New()
		::oWSRETORNO_ALERTAS:SoapRecv(oNode2)
	EndIf
	oNode3 :=  WSAdvValue( oResponse,"_RETORNO_CRITICAS","ARRAYOFCRITICA",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode3 != NIL
		::oWSRETORNO_CRITICAS := WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA():New()
		::oWSRETORNO_CRITICAS:SoapRecv(oNode3)
	EndIf
	oNode4 :=  WSAdvValue( oResponse,"_RETORNO_DADOS","ARRAYOFBENEFICIARIO",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode4 != NIL
		::oWSRETORNO_DADOS := WS_LOGIN_BENEFICIARIO_ARRAYOFBENEFICIARIO():New()
		::oWSRETORNO_DADOS:SoapRecv(oNode4)
	EndIf
	::lRETORNO_STATUS    :=  WSAdvValue( oResponse,"_RETORNO_STATUS","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
Return

// WSDL Data Structure ST_REDEFINE_SENHA

WSSTRUCT WS_LOGIN_BENEFICIARIO_ST_REDEFINE_SENHA
	WSDATA   oWSRETORNO_ALERTAS        AS WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA OPTIONAL
	WSDATA   oWSRETORNO_CRITICAS       AS WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA OPTIONAL
	WSDATA   oWSRETORNO_DADOS          AS WS_LOGIN_BENEFICIARIO_ARRAYOFREDEFINE_SENHA OPTIONAL
	WSDATA   lRETORNO_STATUS           AS boolean OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_ST_REDEFINE_SENHA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_ST_REDEFINE_SENHA
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_ST_REDEFINE_SENHA
	Local oClone := WS_LOGIN_BENEFICIARIO_ST_REDEFINE_SENHA():NEW()
	oClone:oWSRETORNO_ALERTAS   := IIF(::oWSRETORNO_ALERTAS = NIL , NIL , ::oWSRETORNO_ALERTAS:Clone() )
	oClone:oWSRETORNO_CRITICAS  := IIF(::oWSRETORNO_CRITICAS = NIL , NIL , ::oWSRETORNO_CRITICAS:Clone() )
	oClone:oWSRETORNO_DADOS     := IIF(::oWSRETORNO_DADOS = NIL , NIL , ::oWSRETORNO_DADOS:Clone() )
	oClone:lRETORNO_STATUS      := ::lRETORNO_STATUS
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_ST_REDEFINE_SENHA
	Local oNode1
	Local oNode2
	Local oNode3
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNode1 :=  WSAdvValue( oResponse,"_RETORNO_ALERTAS","ARRAYOFALERTA",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode1 != NIL
		::oWSRETORNO_ALERTAS := WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA():New()
		::oWSRETORNO_ALERTAS:SoapRecv(oNode1)
	EndIf
	oNode2 :=  WSAdvValue( oResponse,"_RETORNO_CRITICAS","ARRAYOFCRITICA",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode2 != NIL
		::oWSRETORNO_CRITICAS := WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA():New()
		::oWSRETORNO_CRITICAS:SoapRecv(oNode2)
	EndIf
	oNode3 :=  WSAdvValue( oResponse,"_RETORNO_DADOS","ARRAYOFREDEFINE_SENHA",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode3 != NIL
		::oWSRETORNO_DADOS := WS_LOGIN_BENEFICIARIO_ARRAYOFREDEFINE_SENHA():New()
		::oWSRETORNO_DADOS:SoapRecv(oNode3)
	EndIf
	::lRETORNO_STATUS    :=  WSAdvValue( oResponse,"_RETORNO_STATUS","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFALERTA

WSSTRUCT WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA
	WSDATA   oWSALERTA                 AS WS_LOGIN_BENEFICIARIO_ALERTA OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA
	::oWSALERTA            := {} // Array Of  WS_LOGIN_BENEFICIARIO_ALERTA():New()
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA
	Local oClone := WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA():NEW()
	oClone:oWSALERTA := NIL
	If ::oWSALERTA <> NIL 
		oClone:oWSALERTA := {}
		aEval( ::oWSALERTA , { |x| aadd( oClone:oWSALERTA , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFALERTA
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_ALERTA","ALERTA",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSALERTA , WS_LOGIN_BENEFICIARIO_ALERTA():New() )
			::oWSALERTA[len(::oWSALERTA)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFCRITICA

WSSTRUCT WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA
	WSDATA   oWSCRITICA                AS WS_LOGIN_BENEFICIARIO_CRITICA OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA
	::oWSCRITICA           := {} // Array Of  WS_LOGIN_BENEFICIARIO_CRITICA():New()
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA
	Local oClone := WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA():NEW()
	oClone:oWSCRITICA := NIL
	If ::oWSCRITICA <> NIL 
		oClone:oWSCRITICA := {}
		aEval( ::oWSCRITICA , { |x| aadd( oClone:oWSCRITICA , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFCRITICA
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_CRITICA","CRITICA",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSCRITICA , WS_LOGIN_BENEFICIARIO_CRITICA():New() )
			::oWSCRITICA[len(::oWSCRITICA)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFUSUARIO_ACESSO

WSSTRUCT WS_LOGIN_BENEFICIARIO_ARRAYOFUSUARIO_ACESSO
	WSDATA   oWSUSUARIO_ACESSO         AS WS_LOGIN_BENEFICIARIO_USUARIO_ACESSO OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFUSUARIO_ACESSO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFUSUARIO_ACESSO
	::oWSUSUARIO_ACESSO    := {} // Array Of  WS_LOGIN_BENEFICIARIO_USUARIO_ACESSO():New()
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFUSUARIO_ACESSO
	Local oClone := WS_LOGIN_BENEFICIARIO_ARRAYOFUSUARIO_ACESSO():NEW()
	oClone:oWSUSUARIO_ACESSO := NIL
	If ::oWSUSUARIO_ACESSO <> NIL 
		oClone:oWSUSUARIO_ACESSO := {}
		aEval( ::oWSUSUARIO_ACESSO , { |x| aadd( oClone:oWSUSUARIO_ACESSO , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFUSUARIO_ACESSO
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_USUARIO_ACESSO","USUARIO_ACESSO",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSUSUARIO_ACESSO , WS_LOGIN_BENEFICIARIO_USUARIO_ACESSO():New() )
			::oWSUSUARIO_ACESSO[len(::oWSUSUARIO_ACESSO)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ACESSO

WSSTRUCT WS_LOGIN_BENEFICIARIO_ACESSO
	WSDATA   lACESSA_AGENDAMENTO       AS boolean OPTIONAL
	WSDATA   lACESSA_CARTAO            AS boolean OPTIONAL
	WSDATA   lACESSA_CONSULTA_CARENCIA AS boolean OPTIONAL
	WSDATA   lACESSA_COPARTICIPACAO    AS boolean OPTIONAL
	WSDATA   lACESSA_EDITA_CADASTRO    AS boolean OPTIONAL
	WSDATA   lACESSA_MEDICAMENTO       AS boolean OPTIONAL
	WSDATA   lACESSA_REEMBOLSO         AS boolean OPTIONAL
	WSDATA   lACESSA_TROCA_SENHA       AS boolean OPTIONAL
	WSDATA   lACESSA_UTILIZACAO        AS boolean OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_ACESSO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_ACESSO
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_ACESSO
	Local oClone := WS_LOGIN_BENEFICIARIO_ACESSO():NEW()
	oClone:lACESSA_AGENDAMENTO  := ::lACESSA_AGENDAMENTO
	oClone:lACESSA_CARTAO       := ::lACESSA_CARTAO
	oClone:lACESSA_CONSULTA_CARENCIA := ::lACESSA_CONSULTA_CARENCIA
	oClone:lACESSA_COPARTICIPACAO := ::lACESSA_COPARTICIPACAO
	oClone:lACESSA_EDITA_CADASTRO := ::lACESSA_EDITA_CADASTRO
	oClone:lACESSA_MEDICAMENTO  := ::lACESSA_MEDICAMENTO
	oClone:lACESSA_REEMBOLSO    := ::lACESSA_REEMBOLSO
	oClone:lACESSA_TROCA_SENHA  := ::lACESSA_TROCA_SENHA
	oClone:lACESSA_UTILIZACAO   := ::lACESSA_UTILIZACAO
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_ACESSO
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::lACESSA_AGENDAMENTO :=  WSAdvValue( oResponse,"_ACESSA_AGENDAMENTO","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::lACESSA_CARTAO     :=  WSAdvValue( oResponse,"_ACESSA_CARTAO","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::lACESSA_CONSULTA_CARENCIA :=  WSAdvValue( oResponse,"_ACESSA_CONSULTA_CARENCIA","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::lACESSA_COPARTICIPACAO :=  WSAdvValue( oResponse,"_ACESSA_COPARTICIPACAO","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::lACESSA_EDITA_CADASTRO :=  WSAdvValue( oResponse,"_ACESSA_EDITA_CADASTRO","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::lACESSA_MEDICAMENTO :=  WSAdvValue( oResponse,"_ACESSA_MEDICAMENTO","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::lACESSA_REEMBOLSO  :=  WSAdvValue( oResponse,"_ACESSA_REEMBOLSO","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::lACESSA_TROCA_SENHA :=  WSAdvValue( oResponse,"_ACESSA_TROCA_SENHA","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::lACESSA_UTILIZACAO :=  WSAdvValue( oResponse,"_ACESSA_UTILIZACAO","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFBENEFICIARIO

WSSTRUCT WS_LOGIN_BENEFICIARIO_ARRAYOFBENEFICIARIO
	WSDATA   oWSBENEFICIARIO           AS WS_LOGIN_BENEFICIARIO_BENEFICIARIO OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFBENEFICIARIO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFBENEFICIARIO
	::oWSBENEFICIARIO      := {} // Array Of  WS_LOGIN_BENEFICIARIO_BENEFICIARIO():New()
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFBENEFICIARIO
	Local oClone := WS_LOGIN_BENEFICIARIO_ARRAYOFBENEFICIARIO():NEW()
	oClone:oWSBENEFICIARIO := NIL
	If ::oWSBENEFICIARIO <> NIL 
		oClone:oWSBENEFICIARIO := {}
		aEval( ::oWSBENEFICIARIO , { |x| aadd( oClone:oWSBENEFICIARIO , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFBENEFICIARIO
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_BENEFICIARIO","BENEFICIARIO",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSBENEFICIARIO , WS_LOGIN_BENEFICIARIO_BENEFICIARIO():New() )
			::oWSBENEFICIARIO[len(::oWSBENEFICIARIO)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ARRAYOFREDEFINE_SENHA

WSSTRUCT WS_LOGIN_BENEFICIARIO_ARRAYOFREDEFINE_SENHA
	WSDATA   oWSREDEFINE_SENHA         AS WS_LOGIN_BENEFICIARIO_REDEFINE_SENHA OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFREDEFINE_SENHA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFREDEFINE_SENHA
	::oWSREDEFINE_SENHA    := {} // Array Of  WS_LOGIN_BENEFICIARIO_REDEFINE_SENHA():New()
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFREDEFINE_SENHA
	Local oClone := WS_LOGIN_BENEFICIARIO_ARRAYOFREDEFINE_SENHA():NEW()
	oClone:oWSREDEFINE_SENHA := NIL
	If ::oWSREDEFINE_SENHA <> NIL 
		oClone:oWSREDEFINE_SENHA := {}
		aEval( ::oWSREDEFINE_SENHA , { |x| aadd( oClone:oWSREDEFINE_SENHA , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFREDEFINE_SENHA
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_REDEFINE_SENHA","REDEFINE_SENHA",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSREDEFINE_SENHA , WS_LOGIN_BENEFICIARIO_REDEFINE_SENHA():New() )
			::oWSREDEFINE_SENHA[len(::oWSREDEFINE_SENHA)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure ALERTA

WSSTRUCT WS_LOGIN_BENEFICIARIO_ALERTA
	WSDATA   cALERTA_CODIGO            AS string OPTIONAL
	WSDATA   cALERTA_DESCRICAO         AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_ALERTA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_ALERTA
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_ALERTA
	Local oClone := WS_LOGIN_BENEFICIARIO_ALERTA():NEW()
	oClone:cALERTA_CODIGO       := ::cALERTA_CODIGO
	oClone:cALERTA_DESCRICAO    := ::cALERTA_DESCRICAO
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_ALERTA
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cALERTA_CODIGO     :=  WSAdvValue( oResponse,"_ALERTA_CODIGO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cALERTA_DESCRICAO  :=  WSAdvValue( oResponse,"_ALERTA_DESCRICAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure CRITICA

WSSTRUCT WS_LOGIN_BENEFICIARIO_CRITICA
	WSDATA   lCRITICA_AUTORIZA_CONTATO AS boolean OPTIONAL
	WSDATA   cCRITICA_CODIGO           AS string OPTIONAL
	WSDATA   cCRITICA_DESCRICAO_PROBLEMA AS string OPTIONAL
	WSDATA   cCRITICA_REAL_MOTIVO      AS string OPTIONAL
	WSDATA   cCRITICA_SOLUCAO_PROBLEMA AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_CRITICA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_CRITICA
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_CRITICA
	Local oClone := WS_LOGIN_BENEFICIARIO_CRITICA():NEW()
	oClone:lCRITICA_AUTORIZA_CONTATO := ::lCRITICA_AUTORIZA_CONTATO
	oClone:cCRITICA_CODIGO      := ::cCRITICA_CODIGO
	oClone:cCRITICA_DESCRICAO_PROBLEMA := ::cCRITICA_DESCRICAO_PROBLEMA
	oClone:cCRITICA_REAL_MOTIVO := ::cCRITICA_REAL_MOTIVO
	oClone:cCRITICA_SOLUCAO_PROBLEMA := ::cCRITICA_SOLUCAO_PROBLEMA
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_CRITICA
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::lCRITICA_AUTORIZA_CONTATO :=  WSAdvValue( oResponse,"_CRITICA_AUTORIZA_CONTATO","boolean",NIL,NIL,NIL,"L",NIL,NIL) 
	::cCRITICA_CODIGO    :=  WSAdvValue( oResponse,"_CRITICA_CODIGO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCRITICA_DESCRICAO_PROBLEMA :=  WSAdvValue( oResponse,"_CRITICA_DESCRICAO_PROBLEMA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCRITICA_REAL_MOTIVO :=  WSAdvValue( oResponse,"_CRITICA_REAL_MOTIVO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCRITICA_SOLUCAO_PROBLEMA :=  WSAdvValue( oResponse,"_CRITICA_SOLUCAO_PROBLEMA","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure USUARIO_ACESSO

WSSTRUCT WS_LOGIN_BENEFICIARIO_USUARIO_ACESSO
	WSDATA   cBENEFICIARIO_EMPRESA     AS string OPTIONAL
	WSDATA   cBENEFICIARIO_LOGIN       AS string OPTIONAL
	WSDATA   cBENEFICIARIO_MATRICULA   AS string OPTIONAL
	WSDATA   cBENEFICIARIO_NOME        AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_USUARIO_ACESSO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_USUARIO_ACESSO
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_USUARIO_ACESSO
	Local oClone := WS_LOGIN_BENEFICIARIO_USUARIO_ACESSO():NEW()
	oClone:cBENEFICIARIO_EMPRESA := ::cBENEFICIARIO_EMPRESA
	oClone:cBENEFICIARIO_LOGIN  := ::cBENEFICIARIO_LOGIN
	oClone:cBENEFICIARIO_MATRICULA := ::cBENEFICIARIO_MATRICULA
	oClone:cBENEFICIARIO_NOME   := ::cBENEFICIARIO_NOME
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_USUARIO_ACESSO
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cBENEFICIARIO_EMPRESA :=  WSAdvValue( oResponse,"_BENEFICIARIO_EMPRESA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cBENEFICIARIO_LOGIN :=  WSAdvValue( oResponse,"_BENEFICIARIO_LOGIN","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cBENEFICIARIO_MATRICULA :=  WSAdvValue( oResponse,"_BENEFICIARIO_MATRICULA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cBENEFICIARIO_NOME :=  WSAdvValue( oResponse,"_BENEFICIARIO_NOME","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure BENEFICIARIO

WSSTRUCT WS_LOGIN_BENEFICIARIO_BENEFICIARIO
	WSDATA   cBLOQUEADO                AS string OPTIONAL
	WSDATA   cCARTAO_IMAGEM            AS string OPTIONAL
	WSDATA   cCARTAO_IMAGEM_VERSO      AS string OPTIONAL
	WSDATA   cCARTAO_OBS               AS string OPTIONAL
	WSDATA   cCARTAO_VALIDADE          AS string OPTIONAL
	WSDATA   cCARTAO_VIA               AS string OPTIONAL
	WSDATA   cCONVENIO_ABRANGENCIA     AS string OPTIONAL
	WSDATA   cCONVENIO_ACOMODACAO      AS string OPTIONAL
	WSDATA   cCONVENIO_ANS             AS string OPTIONAL
	WSDATA   oWSCONVENIO_CARENCIAS     AS WS_LOGIN_BENEFICIARIO_ARRAYOFCARENCIA OPTIONAL
	WSDATA   cCONVENIO_DESCRICAO       AS string OPTIONAL
	WSDATA   cCONVENIO_ID              AS string OPTIONAL
	WSDATA   cCONVENIO_MODALIDADE_COBRANCA AS string OPTIONAL
	WSDATA   cCONVENIO_OPCIONAL        AS string OPTIONAL
	WSDATA   cCONVENIO_PADRAO_CONFORTO AS string OPTIONAL
	WSDATA   cCONVENIO_PARTICIPATIVO   AS string OPTIONAL
	WSDATA   cCONVENIO_PERMITE_REEMBOLSO AS string OPTIONAL
	WSDATA   cCONVENIO_SEGMENTACAO     AS string OPTIONAL
	WSDATA   cCONVENIO_TIPO_CONTRATO   AS string OPTIONAL
	WSDATA   cCONVENIO_TIPO_REDE_DESCRICAO AS string OPTIONAL
	WSDATA   cCONVENIO_TIPO_REDE_ID    AS string OPTIONAL
	WSDATA   cCONVENIO_VERSAO          AS string OPTIONAL
	WSDATA   cCPF                      AS string OPTIONAL
	WSDATA   cDATA_CPT                 AS string OPTIONAL
	WSDATA   cDEPENDENCIA_ID           AS string OPTIONAL
	WSDATA   cEMAIL                    AS string OPTIONAL
	WSDATA   cEMPRESA_ID               AS string OPTIONAL
	WSDATA   cEMPRESA_NOME             AS string OPTIONAL
	WSDATA   cEMPRESA_RESPONSAVEL      AS string OPTIONAL
	WSDATA   cEXPIROU_SENHA            AS string OPTIONAL
	WSDATA   cGRAU_PARENTESCO_DESCRICAO AS string OPTIONAL
	WSDATA   cGRAU_PARENTESCO_ID       AS string OPTIONAL
	WSDATA   dINCLUSAO                 AS date OPTIONAL
	WSDATA   cLOGIN                    AS string OPTIONAL
	WSDATA   cMATRICULA                AS string OPTIONAL
	WSDATA   cMATRICULA_FUNCIONARIO    AS string OPTIONAL
	WSDATA   cMOTIVO_BLOQUEIO          AS string OPTIONAL
	WSDATA   dNASCIMENTO               AS date OPTIONAL
	WSDATA   cNOME                     AS string OPTIONAL
	WSDATA   cNUMERO_CNS               AS string OPTIONAL
	WSDATA   cPRONTUARIO_ID            AS string OPTIONAL
	WSDATA   cSEXO                     AS string OPTIONAL
	WSDATA   cSOLICITA_ATUALIZACAO_CADASTRO AS string OPTIONAL
	WSDATA   cTELEFONE                 AS string OPTIONAL
	WSDATA   cTIPO_BENEFICIARIO_DESCRICAO AS string OPTIONAL
	WSDATA   cTIPO_BENEFICIARIO_ID     AS string OPTIONAL
	WSDATA   cTITULAR                  AS string OPTIONAL
	WSDATA   cTITULAR_MATRICULA        AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_BENEFICIARIO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_BENEFICIARIO
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_BENEFICIARIO
	Local oClone := WS_LOGIN_BENEFICIARIO_BENEFICIARIO():NEW()
	oClone:cBLOQUEADO           := ::cBLOQUEADO
	oClone:cCARTAO_IMAGEM       := ::cCARTAO_IMAGEM
	oClone:cCARTAO_IMAGEM_VERSO := ::cCARTAO_IMAGEM_VERSO
	oClone:cCARTAO_OBS          := ::cCARTAO_OBS
	oClone:cCARTAO_VALIDADE     := ::cCARTAO_VALIDADE
	oClone:cCARTAO_VIA          := ::cCARTAO_VIA
	oClone:cCONVENIO_ABRANGENCIA := ::cCONVENIO_ABRANGENCIA
	oClone:cCONVENIO_ACOMODACAO := ::cCONVENIO_ACOMODACAO
	oClone:cCONVENIO_ANS        := ::cCONVENIO_ANS
	oClone:oWSCONVENIO_CARENCIAS := IIF(::oWSCONVENIO_CARENCIAS = NIL , NIL , ::oWSCONVENIO_CARENCIAS:Clone() )
	oClone:cCONVENIO_DESCRICAO  := ::cCONVENIO_DESCRICAO
	oClone:cCONVENIO_ID         := ::cCONVENIO_ID
	oClone:cCONVENIO_MODALIDADE_COBRANCA := ::cCONVENIO_MODALIDADE_COBRANCA
	oClone:cCONVENIO_OPCIONAL   := ::cCONVENIO_OPCIONAL
	oClone:cCONVENIO_PADRAO_CONFORTO := ::cCONVENIO_PADRAO_CONFORTO
	oClone:cCONVENIO_PARTICIPATIVO := ::cCONVENIO_PARTICIPATIVO
	oClone:cCONVENIO_PERMITE_REEMBOLSO := ::cCONVENIO_PERMITE_REEMBOLSO
	oClone:cCONVENIO_SEGMENTACAO := ::cCONVENIO_SEGMENTACAO
	oClone:cCONVENIO_TIPO_CONTRATO := ::cCONVENIO_TIPO_CONTRATO
	oClone:cCONVENIO_TIPO_REDE_DESCRICAO := ::cCONVENIO_TIPO_REDE_DESCRICAO
	oClone:cCONVENIO_TIPO_REDE_ID := ::cCONVENIO_TIPO_REDE_ID
	oClone:cCONVENIO_VERSAO     := ::cCONVENIO_VERSAO
	oClone:cCPF                 := ::cCPF
	oClone:cDATA_CPT            := ::cDATA_CPT
	oClone:cDEPENDENCIA_ID      := ::cDEPENDENCIA_ID
	oClone:cEMAIL               := ::cEMAIL
	oClone:cEMPRESA_ID          := ::cEMPRESA_ID
	oClone:cEMPRESA_NOME        := ::cEMPRESA_NOME
	oClone:cEMPRESA_RESPONSAVEL := ::cEMPRESA_RESPONSAVEL
	oClone:cEXPIROU_SENHA       := ::cEXPIROU_SENHA
	oClone:cGRAU_PARENTESCO_DESCRICAO := ::cGRAU_PARENTESCO_DESCRICAO
	oClone:cGRAU_PARENTESCO_ID  := ::cGRAU_PARENTESCO_ID
	oClone:dINCLUSAO            := ::dINCLUSAO
	oClone:cLOGIN               := ::cLOGIN
	oClone:cMATRICULA           := ::cMATRICULA
	oClone:cMATRICULA_FUNCIONARIO := ::cMATRICULA_FUNCIONARIO
	oClone:cMOTIVO_BLOQUEIO     := ::cMOTIVO_BLOQUEIO
	oClone:dNASCIMENTO          := ::dNASCIMENTO
	oClone:cNOME                := ::cNOME
	oClone:cNUMERO_CNS          := ::cNUMERO_CNS
	oClone:cPRONTUARIO_ID       := ::cPRONTUARIO_ID
	oClone:cSEXO                := ::cSEXO
	oClone:cSOLICITA_ATUALIZACAO_CADASTRO := ::cSOLICITA_ATUALIZACAO_CADASTRO
	oClone:cTELEFONE            := ::cTELEFONE
	oClone:cTIPO_BENEFICIARIO_DESCRICAO := ::cTIPO_BENEFICIARIO_DESCRICAO
	oClone:cTIPO_BENEFICIARIO_ID := ::cTIPO_BENEFICIARIO_ID
	oClone:cTITULAR             := ::cTITULAR
	oClone:cTITULAR_MATRICULA   := ::cTITULAR_MATRICULA
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_BENEFICIARIO
	Local oNode10
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cBLOQUEADO         :=  WSAdvValue( oResponse,"_BLOQUEADO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCARTAO_IMAGEM     :=  WSAdvValue( oResponse,"_CARTAO_IMAGEM","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCARTAO_IMAGEM_VERSO :=  WSAdvValue( oResponse,"_CARTAO_IMAGEM_VERSO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCARTAO_OBS        :=  WSAdvValue( oResponse,"_CARTAO_OBS","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCARTAO_VALIDADE   :=  WSAdvValue( oResponse,"_CARTAO_VALIDADE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCARTAO_VIA        :=  WSAdvValue( oResponse,"_CARTAO_VIA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_ABRANGENCIA :=  WSAdvValue( oResponse,"_CONVENIO_ABRANGENCIA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_ACOMODACAO :=  WSAdvValue( oResponse,"_CONVENIO_ACOMODACAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_ANS      :=  WSAdvValue( oResponse,"_CONVENIO_ANS","string",NIL,NIL,NIL,"S",NIL,NIL) 
	oNode10 :=  WSAdvValue( oResponse,"_CONVENIO_CARENCIAS","ARRAYOFCARENCIA",NIL,NIL,NIL,"O",NIL,NIL) 
	If oNode10 != NIL
		::oWSCONVENIO_CARENCIAS := WS_LOGIN_BENEFICIARIO_ARRAYOFCARENCIA():New()
		::oWSCONVENIO_CARENCIAS:SoapRecv(oNode10)
	EndIf
	::cCONVENIO_DESCRICAO :=  WSAdvValue( oResponse,"_CONVENIO_DESCRICAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_ID       :=  WSAdvValue( oResponse,"_CONVENIO_ID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_MODALIDADE_COBRANCA :=  WSAdvValue( oResponse,"_CONVENIO_MODALIDADE_COBRANCA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_OPCIONAL :=  WSAdvValue( oResponse,"_CONVENIO_OPCIONAL","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_PADRAO_CONFORTO :=  WSAdvValue( oResponse,"_CONVENIO_PADRAO_CONFORTO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_PARTICIPATIVO :=  WSAdvValue( oResponse,"_CONVENIO_PARTICIPATIVO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_PERMITE_REEMBOLSO :=  WSAdvValue( oResponse,"_CONVENIO_PERMITE_REEMBOLSO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_SEGMENTACAO :=  WSAdvValue( oResponse,"_CONVENIO_SEGMENTACAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_TIPO_CONTRATO :=  WSAdvValue( oResponse,"_CONVENIO_TIPO_CONTRATO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_TIPO_REDE_DESCRICAO :=  WSAdvValue( oResponse,"_CONVENIO_TIPO_REDE_DESCRICAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_TIPO_REDE_ID :=  WSAdvValue( oResponse,"_CONVENIO_TIPO_REDE_ID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCONVENIO_VERSAO   :=  WSAdvValue( oResponse,"_CONVENIO_VERSAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cCPF               :=  WSAdvValue( oResponse,"_CPF","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDATA_CPT          :=  WSAdvValue( oResponse,"_DATA_CPT","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cDEPENDENCIA_ID    :=  WSAdvValue( oResponse,"_DEPENDENCIA_ID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cEMAIL             :=  WSAdvValue( oResponse,"_EMAIL","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cEMPRESA_ID        :=  WSAdvValue( oResponse,"_EMPRESA_ID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cEMPRESA_NOME      :=  WSAdvValue( oResponse,"_EMPRESA_NOME","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cEMPRESA_RESPONSAVEL :=  WSAdvValue( oResponse,"_EMPRESA_RESPONSAVEL","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cEXPIROU_SENHA     :=  WSAdvValue( oResponse,"_EXPIROU_SENHA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cGRAU_PARENTESCO_DESCRICAO :=  WSAdvValue( oResponse,"_GRAU_PARENTESCO_DESCRICAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cGRAU_PARENTESCO_ID :=  WSAdvValue( oResponse,"_GRAU_PARENTESCO_ID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::dINCLUSAO          :=  WSAdvValue( oResponse,"_INCLUSAO","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::cLOGIN             :=  WSAdvValue( oResponse,"_LOGIN","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cMATRICULA         :=  WSAdvValue( oResponse,"_MATRICULA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cMATRICULA_FUNCIONARIO :=  WSAdvValue( oResponse,"_MATRICULA_FUNCIONARIO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cMOTIVO_BLOQUEIO   :=  WSAdvValue( oResponse,"_MOTIVO_BLOQUEIO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::dNASCIMENTO        :=  WSAdvValue( oResponse,"_NASCIMENTO","date",NIL,NIL,NIL,"D",NIL,NIL) 
	::cNOME              :=  WSAdvValue( oResponse,"_NOME","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cNUMERO_CNS        :=  WSAdvValue( oResponse,"_NUMERO_CNS","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cPRONTUARIO_ID     :=  WSAdvValue( oResponse,"_PRONTUARIO_ID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cSEXO              :=  WSAdvValue( oResponse,"_SEXO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cSOLICITA_ATUALIZACAO_CADASTRO :=  WSAdvValue( oResponse,"_SOLICITA_ATUALIZACAO_CADASTRO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTELEFONE          :=  WSAdvValue( oResponse,"_TELEFONE","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTIPO_BENEFICIARIO_DESCRICAO :=  WSAdvValue( oResponse,"_TIPO_BENEFICIARIO_DESCRICAO","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTIPO_BENEFICIARIO_ID :=  WSAdvValue( oResponse,"_TIPO_BENEFICIARIO_ID","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTITULAR           :=  WSAdvValue( oResponse,"_TITULAR","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTITULAR_MATRICULA :=  WSAdvValue( oResponse,"_TITULAR_MATRICULA","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure REDEFINE_SENHA

WSSTRUCT WS_LOGIN_BENEFICIARIO_REDEFINE_SENHA
	WSDATA   cBENEFICIARIO_EMAIL       AS string OPTIONAL
	WSDATA   cBENEFICIARIO_NOME        AS string OPTIONAL
	WSDATA   cHASH                     AS string OPTIONAL
	WSDATA   cSENHA                    AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_REDEFINE_SENHA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_REDEFINE_SENHA
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_REDEFINE_SENHA
	Local oClone := WS_LOGIN_BENEFICIARIO_REDEFINE_SENHA():NEW()
	oClone:cBENEFICIARIO_EMAIL  := ::cBENEFICIARIO_EMAIL
	oClone:cBENEFICIARIO_NOME   := ::cBENEFICIARIO_NOME
	oClone:cHASH                := ::cHASH
	oClone:cSENHA               := ::cSENHA
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_REDEFINE_SENHA
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cBENEFICIARIO_EMAIL :=  WSAdvValue( oResponse,"_BENEFICIARIO_EMAIL","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cBENEFICIARIO_NOME :=  WSAdvValue( oResponse,"_BENEFICIARIO_NOME","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cHASH              :=  WSAdvValue( oResponse,"_HASH","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cSENHA             :=  WSAdvValue( oResponse,"_SENHA","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return

// WSDL Data Structure ARRAYOFCARENCIA

WSSTRUCT WS_LOGIN_BENEFICIARIO_ARRAYOFCARENCIA
	WSDATA   oWSCARENCIA               AS WS_LOGIN_BENEFICIARIO_CARENCIA OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFCARENCIA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFCARENCIA
	::oWSCARENCIA          := {} // Array Of  WS_LOGIN_BENEFICIARIO_CARENCIA():New()
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFCARENCIA
	Local oClone := WS_LOGIN_BENEFICIARIO_ARRAYOFCARENCIA():NEW()
	oClone:oWSCARENCIA := NIL
	If ::oWSCARENCIA <> NIL 
		oClone:oWSCARENCIA := {}
		aEval( ::oWSCARENCIA , { |x| aadd( oClone:oWSCARENCIA , x:Clone() ) } )
	Endif 
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_ARRAYOFCARENCIA
	Local nRElem1, oNodes1, nTElem1
	::Init()
	If oResponse = NIL ; Return ; Endif 
	oNodes1 :=  WSAdvValue( oResponse,"_CARENCIA","CARENCIA",{},NIL,.T.,"O",NIL,NIL) 
	nTElem1 := len(oNodes1)
	For nRElem1 := 1 to nTElem1 
		If !WSIsNilNode( oNodes1[nRElem1] )
			aadd(::oWSCARENCIA , WS_LOGIN_BENEFICIARIO_CARENCIA():New() )
			::oWSCARENCIA[len(::oWSCARENCIA)]:SoapRecv(oNodes1[nRElem1])
		Endif
	Next
Return

// WSDL Data Structure CARENCIA

WSSTRUCT WS_LOGIN_BENEFICIARIO_CARENCIA
	WSDATA   cCARENCIA                 AS string OPTIONAL
	WSDATA   cTIPO_SERVICO             AS string OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WS_LOGIN_BENEFICIARIO_CARENCIA
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WS_LOGIN_BENEFICIARIO_CARENCIA
Return

WSMETHOD CLONE WSCLIENT WS_LOGIN_BENEFICIARIO_CARENCIA
	Local oClone := WS_LOGIN_BENEFICIARIO_CARENCIA():NEW()
	oClone:cCARENCIA            := ::cCARENCIA
	oClone:cTIPO_SERVICO        := ::cTIPO_SERVICO
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WS_LOGIN_BENEFICIARIO_CARENCIA
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::cCARENCIA          :=  WSAdvValue( oResponse,"_CARENCIA","string",NIL,NIL,NIL,"S",NIL,NIL) 
	::cTIPO_SERVICO      :=  WSAdvValue( oResponse,"_TIPO_SERVICO","string",NIL,NIL,NIL,"S",NIL,NIL) 
Return


